version: "3.5"

services:
    # Core configuration
    php-fpm:
        container_name: ${CONTAINER_NAME}_php-fpm
        build: .
        environment:
            PHP_XDEBUG_ENABLED: 1
            PHP_IDE_CONFIG: serverName=localhost
        ports:
            - '${PHP_PORT}:9000'
        volumes:
            - './:${WORKPATH}:rw'
        restart: always

    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx
        ports:
            - '${NGINX_PORT}:80'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:rw'
            - './docker/nginx/conf/core/core.conf:/etc/nginx/conf/nginx.conf:ro'
            - './docker/nginx/conf/development:/etc/nginx/conf.d:ro'
            # - './docker/nginx/conf/production:/etc/nginx/conf.d:ro' -> Uncomment this line for production.
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    # Frontend configuration
    node:
        container_name: ${CONTAINER_NAME}_nodejs
        build: './docker/node'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:rw'
        working_dir: ${WORKPATH}



    # MysqlDB Configuration
    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mysql:5.7.28
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_NAME}
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - 'mysqlproject:/var/lib/mysql:rw'

volumes:
    mysqlproject:
